name: Rust build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3   

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal  # Minimal installation to speed up CI
          toolchain: stable  # Use stable version, or adjust to a specific version if needed
          components: clippy, rustfmt

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run examples (optional)
        run: cargo run --example no-modules  # Replace 'no-modules' with the correct example

      - name: Lint
        run: cargo clippy --all-targets --verbose

      - name: Format
        run: cargo fmt --all --verbose

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Check for unused dependencies
        run: cargo audit --verbose
